export interface TreatmentBannerInfo {
  label: string;
  desktop: string;
  mobile: string;
  alt: string;
  width: number;
  height: number;
  mobileWidth: number;
  mobileHeight: number;
  heroAlignment?: "left" | "right";
}

export const treatmentBanners = {
  "facetas-de-resina": {
    label: "Facetas de Resina e Lentes em Resina",
    desktop: "/images/treatments/facetas-de-resina/hero-desktop.webp",
    mobile: "/images/treatments/facetas-de-resina/hero-mobile.webp",
    alt: "Avaliação estética do sorriso com escala de tonalidades dentárias",
    width: 1600,
    height: 900,
    mobileWidth: 900,
    mobileHeight: 1600,
    heroAlignment: "left",
  },
  "lentes-de-contato-dental": {
    label: "Lentes de Contato Dental e Facetas de Porcelana",
    desktop: "/images/treatments/lentes-de-contato-dental/hero-desktop.webp",
    mobile: "/images/treatments/lentes-de-contato-dental/hero-mobile.webp",
    alt: "Exame e planejamento estético dental com lâminas e facetas cerâmicas",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "clareamento-dental": {
    label: "Clareamento Dental",
    desktop: "/images/treatments/clareamento-dental/hero-desktop.webp",
    mobile: "/images/treatments/clareamento-dental/hero-mobile.webp",
    alt: "Procedimento clínico de clareamento dental com iluminação odontológica",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "fechamento-de-diastemas": {
    label: "Fechamento de Diastemas",
    desktop: "/images/treatments/fechamento-de-diastemas/hero-desktop.webp",
    mobile: "/images/treatments/fechamento-de-diastemas/hero-mobile.webp",
    alt: "Avaliação odontológica de espaçamento entre os dentes anteriores",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "implantes-dentarios": {
    label: "Implantes Dentários",
    desktop: "/images/treatments/implantes-dentarios/hero-desktop.webp",
    mobile: "/images/treatments/implantes-dentarios/hero-mobile.webp",
    alt: "Paciente adulto em consulta de planejamento para implantes dentários",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "protese-protocolo": {
    label: "Prótese Protocolo",
    desktop: "/images/treatments/protese-protocolo/hero-desktop.webp",
    mobile: "/images/treatments/protese-protocolo/hero-mobile.webp",
    alt: "Reabilitação oral com prótese sobre implantes dentários",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "enxerto-osseo-dentario": {
    label: "Enxerto Ósseo para Implantes",
    desktop: "/images/treatments/enxerto-osseo-dentario/hero-desktop.webp",
    mobile: "/images/treatments/enxerto-osseo-dentario/hero-mobile.webp",
    alt: "Planejamento cirúrgico para regeneração e enxerto ósseo dentário",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "proteses-dentarias": {
    label: "Próteses Dentárias",
    desktop: "/images/treatments/proteses-dentarias/hero-desktop.webp",
    mobile: "/images/treatments/proteses-dentarias/hero-mobile.webp",
    alt: "Consulta odontológica para confecção e ajuste de prótese dentária",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "inlays-onlays": {
    label: "Inlays e Onlays / Restaurações Indiretas",
    desktop: "/images/treatments/inlays-onlays/hero-desktop.webp",
    mobile: "/images/treatments/inlays-onlays/hero-mobile.webp",
    alt: "Demonstração clínica de restauração indireta em porcelana",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "reabilitacao-oral": {
    label: "Reabilitação Oral",
    desktop: "/images/treatments/reabilitacao-oral/hero-desktop.webp",
    mobile: "/images/treatments/reabilitacao-oral/hero-mobile.webp",
    alt: "Planejamento integrado de reabilitação e harmonia do sorriso",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "ortodontia": {
    label: "Ortodontia / Aparelhos e Alinhadores",
    desktop: "/images/treatments/ortodontia/hero-desktop.webp",
    mobile: "/images/treatments/ortodontia/hero-mobile.webp",
    alt: "Planejamento ortodôntico com avaliação da oclusão e posicionamento dental",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "invisalign": {
    label: "Invisalign / Alinhadores Transparentes",
    desktop: "/images/treatments/invisalign/hero-desktop.webp",
    mobile: "/images/treatments/invisalign/hero-mobile.webp",
    alt: "Alinhadores transparentes utilizados em tratamento ortodôntico",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "manutencao-odontologica": {
    label: "Manutenção e Acompanhamento Odontológico",
    desktop: "/images/treatments/manutencao-odontologica/hero-desktop.webp",
    mobile: "/images/treatments/manutencao-odontologica/hero-mobile.webp",
    alt: "Consulta de acompanhamento e manutenção preventiva odontológica",
    width: 1672,
    height: 940,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "limpeza-dental": {
    label: "Limpeza Dental / Profilaxia",
    desktop: "/images/treatments/limpeza-dental/hero-desktop.webp",
    mobile: "/images/treatments/limpeza-dental/hero-mobile.webp",
    alt: "Atendimento clínico para profilaxia e limpeza dentária profissional",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "periodontia": {
    label: "Periodontia / Tratamento de Gengiva",
    desktop: "/images/treatments/periodontia/hero-desktop.webp",
    mobile: "/images/treatments/periodontia/hero-mobile.webp",
    alt: "Exame clínico e avaliação da saúde dos tecidos gengivais",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "cirurgia-gengival": {
    label: "Gengivoplastia e Cirurgia Gengival",
    desktop: "/images/treatments/cirurgia-gengival/hero-desktop.webp",
    mobile: "/images/treatments/cirurgia-gengival/hero-mobile.webp",
    alt: "Planejamento clínico para gengivoplastia e alinhamento do contorno gengival",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "tratamento-de-canal": {
    label: "Tratamento de Canal / Endodontia",
    desktop: "/images/treatments/tratamento-de-canal/hero-desktop.webp",
    mobile: "/images/treatments/tratamento-de-canal/hero-mobile.webp",
    alt: "Atendimento endodôntico para preservação da estrutura dental",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "extracao-de-siso": {
    label: "Extração de Siso",
    desktop: "/images/treatments/extracao-de-siso/hero-desktop.webp",
    mobile: "/images/treatments/extracao-de-siso/hero-mobile.webp",
    alt: "Avaliação odontológica para extração segura de terceiros molares",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "bruxismo": {
    label: "Bruxismo, DTM e Dor Orofacial",
    desktop: "/images/treatments/bruxismo/hero-desktop.webp",
    mobile: "/images/treatments/bruxismo/hero-mobile.webp",
    alt: "Consulta clínica para diagnóstico e tratamento de bruxismo e dor orofacial",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "harmonizacao-facial": {
    label: "Harmonização Facial",
    desktop: "/images/treatments/harmonizacao-facial/hero-desktop.webp",
    mobile: "/images/treatments/harmonizacao-facial/hero-mobile.webp",
    alt: "Análise estética das proporções e equilíbrio do terço facial",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "preenchimento-facial": {
    label: "Preenchimento Facial",
    desktop: "/images/treatments/preenchimento-facial/hero-desktop.webp",
    mobile: "/images/treatments/preenchimento-facial/hero-mobile.webp",
    alt: "Procedimento clínico de preenchimento facial com ácido hialurônico",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "preenchimento-labial": {
    label: "Preenchimento Labial",
    desktop: "/images/treatments/preenchimento-labial/hero-desktop.webp",
    mobile: "/images/treatments/preenchimento-labial/hero-mobile.webp",
    alt: "Avaliação e planejamento de contorno e proporção labial",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "botox": {
    label: "Botox / Toxina Botulínica e Linhas de Expressão",
    desktop: "/images/treatments/botox/hero-desktop.webp",
    mobile: "/images/treatments/botox/hero-mobile.webp",
    alt: "Aplicação planejada de toxina botulínica para linhas de expressão faciais",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "bioestimuladores-de-colageno": {
    label: "Bioestimuladores de Colágeno",
    desktop: "/images/treatments/bioestimuladores-de-colageno/hero-desktop.webp",
    mobile: "/images/treatments/bioestimuladores-de-colageno/hero-mobile.webp",
    alt: "Aplicação de bioestimulador de colágeno para firmeza da pele facial",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
  "perfiloplastia": {
    label: "Perfiloplastia",
    desktop: "/images/treatments/perfiloplastia/hero-desktop.webp",
    mobile: "/images/treatments/perfiloplastia/hero-mobile.webp",
    alt: "Avaliação do perfil facial integrando nariz, lábios e mento",
    width: 1672,
    height: 941,
    mobileWidth: 941,
    mobileHeight: 1672,
    heroAlignment: "left",
  },
} as const;

export type TreatmentBannerSlug = keyof typeof treatmentBanners;

export function getTreatmentBanner(slug: string): TreatmentBannerInfo | null {
  return (treatmentBanners as Record<string, TreatmentBannerInfo>)[slug] ?? null;
}

/**
 * Ajustes de enquadramento 4:3 para destacar o modelo e o procedimento clínico em cards de visão geral.
 * Como os banners 16:9 originais concentram o sujeito/procedimento à direita e o espaço negativo
 * de leitura à esquerda, o enquadramento deslocado para a direita (~80%-85%) centraliza o modelo na thumbnail.
 */
export const treatmentThumbnailPosition: Record<string, string> = {
  // Tratamentos com foco no modelo, tela 3D e paciente bem à direita
  "implantes-dentarios": "85% center",
  "proteses-dentarias": "85% center",
  "reabilitacao-oral": "85% center",
  "enxerto-osseo-dentario": "85% center",
  "manutencao-odontologica": "85% center",
  "tratamento-de-canal": "85% center",
  "extracao-de-siso": "85% center",
  "bruxismo": "85% center",
  
  // Tratamentos com foco intermediário à direita
  "limpeza-dental": "80% center",
  "periodontia": "80% 40%",
  "cirurgia-gengival": "80% 40%",
  "facetas-de-resina": "80% center",
  "lentes-de-contato-dental": "80% center",
  "clareamento-dental": "80% center",
  "ortodontia": "80% center",
  "protese-protocolo": "75% center",
  "invisalign": "75% center",
  "inlays-onlays": "75% center",
  "fechamento-de-diastemas": "70% center",

  // Estética Orofacial
  "harmonizacao-facial": "75% center",
  "preenchimento-facial": "75% center",
  "preenchimento-labial": "75% center",
  "botox": "75% center",
  "bioestimuladores-de-colageno": "75% 40%",
  "perfiloplastia": "75% center",
};

export function getTreatmentThumbnailPosition(slug: string): string {
  return treatmentThumbnailPosition[slug] ?? "80% center";
}